name: example
description: Example of nd_authentications.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: 
  nd_authentications:
    path: '..'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  rename: ^2.0.0

flutter:

  uses-material-design: true
