// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0L7uehfomMRDR6aXBZnA8iUBC3FkGSHc',
    appId: '1:590918060163:web:e07c59c3fd974496b7b3b6',
    messagingSenderId: '590918060163',
    projectId: 'fir-playground-cab3a',
    authDomain: 'fir-playground-cab3a.firebaseapp.com',
    databaseURL: 'https://fir-playground-cab3a.firebaseio.com',
    storageBucket: 'fir-playground-cab3a.appspot.com',
    measurementId: 'G-01C095DZ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoM9uIf_1JX6YXlO6fDzrjKSP1Wg5ouwA',
    appId: '1:590918060163:android:f35dd7d9bdd76760b7b3b6',
    messagingSenderId: '590918060163',
    projectId: 'fir-playground-cab3a',
    databaseURL: 'https://fir-playground-cab3a.firebaseio.com',
    storageBucket: 'fir-playground-cab3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSf8CfpK5D-39mKY4bmTTT1NuZEhgc_E',
    appId: '1:590918060163:ios:90b80b523abf329fb7b3b6',
    messagingSenderId: '590918060163',
    projectId: 'fir-playground-cab3a',
    databaseURL: 'https://fir-playground-cab3a.firebaseio.com',
    storageBucket: 'fir-playground-cab3a.appspot.com',
    iosClientId: '590918060163-cnl7nm6ek5328a22075p10m9qfa2t1ud.apps.googleusercontent.com',
    iosBundleId: 'vn.neodata.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOSf8CfpK5D-39mKY4bmTTT1NuZEhgc_E',
    appId: '1:590918060163:ios:90b80b523abf329fb7b3b6',
    messagingSenderId: '590918060163',
    projectId: 'fir-playground-cab3a',
    databaseURL: 'https://fir-playground-cab3a.firebaseio.com',
    storageBucket: 'fir-playground-cab3a.appspot.com',
    iosClientId: '590918060163-cnl7nm6ek5328a22075p10m9qfa2t1ud.apps.googleusercontent.com',
    iosBundleId: 'vn.neodata.example',
  );
}
